### ISSUE TITLE
i get this error after running program.js an the button doesnt add   to the todolist

### ISSUE THREAD

**Issue by Osezno** [workshopper/learnyoureact#102]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module '/home/jose/reactdos/isomorphic/solution/app.js' from '/home/jose/reactdos'
    at /home/jose/reactdos/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/home/jose/reactdos/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/jose/reactdos/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /home/jose/reactdos/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by lolptdr** [comment]
Need more detail.

1) Which lesson is this referring to?
2) Can you post the app.js, index.jsx, program.js, etc. files?
