### ISSUE TITLE
Trouble running lesson 8 (supposedly Babel error)

### ISSUE THREAD

**Issue by lessthanzero** [workshopper/learnyoureact#104]
Hi! My setup is `node 4.4.4` and `learnyoureact 0.11.6`.

I have trouble running my project in browser starting with lesson 8. Code verifies successfully, but when I try to load page, I constantly get an error (both in 8 and 9 lessons):

![learnyoureact-error-8](https://cloud.githubusercontent.com/assets/1044864/15706452/50075ace-27fc-11e6-9eba-8430faba2836.png)

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'error' of undefined while parsing file: /Users/user/Developer/learnyoureact/app.js
    at OptionManager.mergeOptions (/Users/user/Developer/learnyoureact/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/Users/user/Developer/learnyoureact/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/Users/user/Developer/learnyoureact/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/Users/user/Developer/learnyoureact/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/Users/user/Developer/learnyoureact/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/Users/user/Developer/learnyoureact/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/user/Developer/learnyoureact/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

Looks like a Babel error, so I've tried to downgrade to `babel 5.8.23` from `5.8.38` but to no avail.

Also, when I run `npm list` I get peer invalid messages:

![peer-invalid](https://cloud.githubusercontent.com/assets/1044864/15706580/0703afb6-27fd-11e6-9c3b-fe1cbfb236df.png)

```
├─┬ react@15.1.0 peer invalid
│ ├─┬ fbjs@0.8.3
│ │ ├── core-js@1.2.6
│ │ ├── immutable@3.8.1
│ │ ├─┬ isomorphic-fetch@2.2.1
│ │ │ ├─┬ node-fetch@1.5.3
│ │ │ │ ├─┬ encoding@0.1.12
│ │ │ │ │ └── iconv-lite@0.4.13
│ │ │ │ └── is-stream@1.1.0
│ │ │ └── whatwg-fetch@1.0.0
│ │ ├─┬ promise@7.1.1
│ │ │ └── asap@2.0.4
│ │ └── ua-parser-js@0.7.10
│ ├─┬ loose-envify@1.2.0
│ │ └── js-tokens@1.0.3
│ └── object-assign@4.1.0
└── react-dom@15.1.0 peer invalid

npm ERR! peer invalid: react@15.1.0 /Users/user/Developer/learnyoureact/node_modules/react
npm ERR! peer invalid: react-dom@15.1.0 /Users/user/Developer/learnyoureact/node_modules/react-dom
npm ERR! extraneous: browserify@13.0.1 /Users/user/Developer/learnyoureact/node_modules/browserify
npm ERR! extraneous: babelify@7.3.0 /Users/user/Developer/learnyoureact/node_modules/babelify
npm ERR! extraneous: babel-preset-react@6.5.0 /Users/user/Developer/learnyoureact/node_modules/babel-preset-react
npm ERR! extraneous: babel-preset-es2015@6.9.0 /Users/user/Developer/learnyoureact/node_modules/babel-preset-es2015
```

Anyone saw something like this? What should I do?

Thanks!

**Comment by rvdpeijl** [comment]
+1

**Comment by delaguilaluis** [comment]
Had the same problem and solved it by following [this suggestion](https://github.com/kohei-takata/learnyoureact/issues/103#issuecomment-239604351).

**Comment by house92** [comment]
I'm seeing the same problem, and wiping my node_modules and reinstalling hasn't fixed it :/ Anybody made any headway with this?

**Comment by delaguilaluis** [comment]
Are you using this dependencies versions?

```json
"dependencies": {
    "babel": "^5.8.23",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-react": "^6.1.18",
    "babelify": "^7.2.0",
    "body-parser": "^1.15.2",
    "browserify": "^13.1.1",
    "express": "^4.14.0",
    "express-react-views": "^0.9.0",
    "react": "^0.14.0",
    "react-dom": "^0.14.0"
  }
```

**Comment by lessthanzero** [comment]
@delaguilaluis worked fine! Thanks
