### ISSUE TITLE
Cannot find module 'regenerator/runtime'

### ISSUE THREAD

**Issue by aTylerRice** [workshopper/learnyoureact#52]
I keep getting this error when I try to run the 1st lesson.

Here is the full error:
`Error: Cannot find module 'regenerator/runtime'
   at Function.Module._resolveFilename (module.js:336:15)
   at Function.Module._load (module.js:278:25)
   at Module.require (module.js:365:17)
   at require (module.js:384:17)
   at Object.<anonymous> (/Users/tylerrice/Desktop/learnyoureact/node_modules/express-react-views/node_modules/babel/node_modules/babel-core/lib/polyfill.js:5:1)
   at Module._compile (module.js:460:26)
   at Object.require.extensions.(anonymous function) [as .js] (/Users/tylerrice/Desktop/learnyoureact/node_modules/node-jsx/index.js:29:12)
   at Module.load (module.js:355:32)
   at Function.Module._load (module.js:310:12)
   at Module.require (module.js:365:17)
   at require (module.js:384:17)`

**Comment by kohei-takata** [comment]
Which version did you use?
Please try to update and use latest version.
