### ISSUE TITLE
Error: Cannot find module 'minimist'

### ISSUE THREAD

**Issue by jatins** [workshopper/learnyoureact#86]
Installed with `sudo npm i -g learnyoureact` but when I try to run it with `learnyoureact`, getting this error:

```
Error: Cannot find module 'minimist'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/learnyoureact/node_modules/workshopper-adventure/adventure.js:1:84)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
```

node v5.0.0
npm  v3.3.6

**Comment by kohei-takata** [comment]
Hi @jatins !
Thank you for your reporting issue.
But I can't reproduce the error :cry: 
Could you try `sudo npm uninstall -g learnyoureact` and `sudo npm i -g learnyoureact` again?

**Comment by jatins** [comment]
Well, uninstalling and installing again did the trick.
Any idea why that might have happened?

**Comment by kohei-takata** [comment]
@jatins 
I think installing didn't end correctly(caused by network, your machine or etc...).
