### ISSUE TITLE
`Props from server` error: map function cannot be applied to undefined.

### ISSUE THREAD

**Issue by yask123** [workshopper/learnyoureact#87]
I am getting this error on exercise 7:

```
`Props from server` error: map function cannot be applied to undefined.
```

I tried running your solution file, but I am still getting the error.
Maybe data is not being passed to the view ?
How can I test in `jsx` file that data has been passed correctly ?

Error Logs:

```
TypeError: Cannot read property 'map' of undefined
   at TodoList.render (/Users/yasksrivastava/learnyoureact/views/index.jsx:17:35)
   at [object Object].ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (/Users/yasksrivastava/learnyoureact/node_modules/react/lib/ReactCompositeComponent.js:587:34)
   at [object Object].ReactCompositeComponentMixin._renderValidatedComponent (/Users/yasksrivastava/learnyoureact/node_modules/react/lib/ReactCompositeComponent.js:607:32)
   at [object Object].wrapper [as _renderValidatedComponent] (/Users/yasksrivastava/learnyoureact/node_modules/react/lib/ReactPerf.js:66:21)
   at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/yasksrivastava/learnyoureact/node_modules/react/lib/ReactCompositeComponent.js:220:30)
   at [object Object].wrapper [as mountComponent] (/Users/yasksrivastava/learnyoureact/node_modules/react/lib/ReactPerf.js:66:21)
   at Object.ReactReconciler.mountComponent (/Users/yasksrivastava/learnyoureact/node_modules/react/lib/ReactReconciler.js:37:35)
   at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/Users/yasksrivastava/learnyoureact/node_modules/react/lib/ReactMultiChild.js:241:44)
   at ReactDOMComponent.Mixin._createContentMarkup (/Users/yasksrivastava/learnyoureact/node_modules/react/lib/ReactDOMComponent.js:591:32)
   at ReactDOMComponent.Mixin.mountComponent (/Users/yasksrivastava/learnyoureact/node_modules/react/lib/ReactDOMComponent.js:479:29)
```

Thanks.

**Comment by yask123** [comment]
Whoops! I restarted my computer, and it worked.
Strange.!
